[book]
authors = ["Sytse Reitsma"]
multilingual = false
src = "src"
title = "Notes"

[build]
create-missing = false

[output.html]
additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
